version: "3.7"

services:
  database:
    image: postgres
    container_name: database_reactmon
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=reactmon
      - POSTGRES_DB=reactmon
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: reactmon
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local