const SeedPokemons = [
  {
    height: '0.89',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Abra',
    weight: '19.5',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Abra.png',
  },
  {
    height: '1.80',
    weakness: '["Water", "Electric", "Ice", "Rock", "Steel"]',
    name: 'Aerodactyl',
    weight: '59.0',
    types: '["Rock", "Flying"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Aerodactyl.png',
  },
  {
    height: '1.50',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Alakazam',
    weight: '48.0',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Alakazam.png',
  },
  {
    height: '3.51',
    weakness: '["Ground", "Psychic"]',
    name: 'Arbok',
    weight: '65.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Arbok.png',
  },
  {
    height: '1.91',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Arcanine',
    weight: '155.0',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Arcanine.png',
  },
  {
    height: '1.70',
    weakness: '["Fire", "Electric", "Rock", "Steel"]',
    name: 'Articuno',
    weight: '55.4',
    types: '["Ice", "Flying"]',
    mainType: 'Ice',
    image: 'e3aa059cc520f04244e4-Articuno.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Flying", "Psychic", "Rock"]',
    name: 'Beedrill',
    weight: '29.5',
    types: '["Bug", "Poison"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Beedrill.png',
  },
  {
    height: '0.71',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Bellsprout',
    weight: '4.0',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Bellsprout.png',
  },
  {
    height: '1.60',
    weakness: '["Electric", "Grass"]',
    name: 'Blastoise',
    weight: '85.5',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Blastoise.png',
  },
  {
    height: '0.71',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Bulbasaur',
    weight: '6.9',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Bulbasaur.png',
  },
  {
    height: '1.09',
    weakness: '["Fire", "Electric", "Ice", "Flying", "Rock"]',
    name: 'Butterfree',
    weight: '32.0',
    types: '["Bug", "Flying"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Butterfree.png',
  },
  {
    height: '0.30',
    weakness: '["Fire", "Flying", "Rock"]',
    name: 'Caterpie',
    weight: '2.9',
    types: '["Bug"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Caterpie.png',
  },
  {
    height: '1.09',
    weakness: '["Fighting"]',
    name: 'Chansey',
    weight: '34.6',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Chansey.png',
  },
  {
    height: '1.70',
    weakness: '["Water", "Electric", "Rock"]',
    name: 'Charizard',
    weight: '90.5',
    types: '["Fire", "Flying"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Charizard.png',
  },
  {
    height: '0.61',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Charmander',
    weight: '8.5',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Charmander.png',
  },
  {
    height: '1.09',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Charmeleon',
    weight: '19.0',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Charmeleon.png',
  },
  {
    height: '1.30',
    weakness: '["Fighting"]',
    name: 'Clefable',
    weight: '40.0',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Clefable.png',
  },
  {
    height: '0.61',
    weakness: '["Fighting"]',
    name: 'Clefairy',
    weight: '7.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Clefairy.png',
  },
  {
    height: '1.50',
    weakness: '["Electric", "Grass", "Fighting", "Rock"]',
    name: 'Cloyster',
    weight: '132.5',
    types: '["Water", "Ice"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Cloyster.png',
  },
  {
    height: '0.41',
    weakness: '["Water", "Grass", "Ice"]',
    name: 'Cubone',
    weight: '6.5',
    types: '["Ground"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Cubone.png',
  },
  {
    height: '1.70',
    weakness: '["Electric", "Grass", "Fighting", "Rock"]',
    name: 'Dewgong',
    weight: '120.0',
    types: '["Water", "Ice"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Dewgong.png',
  },
  {
    height: '0.20',
    weakness: '["Water", "Grass", "Ice"]',
    name: 'Diglett',
    weight: '0.8',
    types: '["Ground"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Diglett.png',
  },
  {
    height: '0.30',
    weakness: '["Fighting"]',
    name: 'Ditto',
    weight: '4.0',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Ditto.png',
  },
  {
    height: '1.80',
    weakness: '["Electric", "Rock"]',
    name: 'Dodrio',
    weight: '85.2',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Dodrio.png',
  },
  {
    height: '1.40',
    weakness: '["Electric", "Rock"]',
    name: 'Doduo',
    weight: '39.2',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Doduo.png',
  },
  {
    height: '3.99',
    weakness: '["Ice", "Dragon", "Fairy"]',
    name: 'Dragonair',
    weight: '16.5',
    types: '["Dragon"]',
    mainType: 'Dragon',
    image: 'e3aa059cc520f04244e4-Dragonair.png',
  },
  {
    height: '2.21',
    weakness: '["Ice", "Rock", "Dragon", "Fairy"]',
    name: 'Dragonite',
    weight: '210.0',
    types: '["Dragon", "Flying"]',
    mainType: 'Dragon',
    image: 'e3aa059cc520f04244e4-Dragonite.png',
  },
  {
    height: '1.80',
    weakness: '["Ice", "Dragon", "Fairy"]',
    name: 'Dratini',
    weight: '3.3',
    types: '["Dragon"]',
    mainType: 'Dragon',
    image: 'e3aa059cc520f04244e4-Dratini.png',
  },
  {
    height: '0.99',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Drowzee',
    weight: '32.4',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Drowzee.png',
  },
  {
    height: '0.71',
    weakness: '["Water", "Grass", "Ice"]',
    name: 'Dugtrio',
    weight: '33.3',
    types: '["Ground"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Dugtrio.png',
  },
  {
    height: '0.30',
    weakness: '["Fighting"]',
    name: 'Eevee',
    weight: '6.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Eevee.png',
  },
  {
    height: '2.01',
    weakness: '["Ground", "Psychic"]',
    name: 'Ekans',
    weight: '6.9',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Ekans.png',
  },
  {
    height: '1.09',
    weakness: '["Ground"]',
    name: 'Electabuzz',
    weight: '30.0',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Electabuzz.png',
  },
  {
    height: '1.19',
    weakness: '["Ground"]',
    name: 'Electrode',
    weight: '66.6',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Electrode.png',
  },
  {
    height: '0.41',
    weakness: '["Fire", "Ice", "Poison", "Flying", "Bug", "Ghost", "Dark"]',
    name: 'Exeggcute',
    weight: '2.5',
    types: '["Grass", "Psychic"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Exeggcute.png',
  },
  {
    height: '2.01',
    weakness: '["Fire", "Ice", "Poison", "Flying", "Bug", "Ghost", "Dark"]',
    name: 'Exeggutor',
    weight: '120.0',
    types: '["Grass", "Psychic"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Exeggutor.png',
  },
  {
    height: '0.79',
    weakness: '["Electric", "Rock"]',
    name: 'Farfetch',
    weight: '15.0',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Farfetch.png',
  },
  {
    height: '1.19',
    weakness: '["Electric", "Rock"]',
    name: 'Fearow',
    weight: '38.0',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Fearow.png',
  },
  {
    height: '0.89',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Flareon',
    weight: '25.0',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Flareon.png',
  },
  {
    height: '1.30',
    weakness: '["Ground", "Psychic", "Ghost", "Dark"]',
    name: 'Gastly',
    weight: '0.1',
    types: '["Ghost", "Poison"]',
    mainType: 'Ghost',
    image: 'e3aa059cc520f04244e4-Gastly.png',
  },
  {
    height: '1.50',
    weakness: '["Ground", "Psychic", "Ghost", "Dark"]',
    name: 'Gengar',
    weight: '40.5',
    types: '["Ghost", "Poison"]',
    mainType: 'Ghost',
    image: 'e3aa059cc520f04244e4-Gengar.png',
  },
  {
    height: '0.41',
    weakness: '["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"]',
    name: 'Geodude',
    weight: '20.0',
    types: '["Rock", "Ground"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Geodude.png',
  },
  {
    height: '0.79',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Gloom',
    weight: '8.6',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Gloom.png',
  },
  {
    height: '1.60',
    weakness: '["Electric", "Ice", "Psychic", "Rock"]',
    name: 'Golbat',
    weight: '55.0',
    types: '["Poison", "Flying"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Golbat.png',
  },
  {
    height: '0.61',
    weakness: '["Electric", "Grass"]',
    name: 'Goldeen',
    weight: '15.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Goldeen.png',
  },
  {
    height: '1.70',
    weakness: '["Electric", "Grass"]',
    name: 'Golduck',
    weight: '76.6',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Golduck.png',
  },
  {
    height: '1.40',
    weakness: '["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"]',
    name: 'Golem',
    weight: '300.0',
    types: '["Rock", "Ground"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Golem.png',
  },
  {
    height: '0.99',
    weakness: '["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"]',
    name: 'Graveler',
    weight: '105.0',
    types: '["Rock", "Ground"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Graveler.png',
  },
  {
    height: '0.89',
    weakness: '["Ground", "Psychic"]',
    name: 'Grimer',
    weight: '30.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Grimer.png',
  },
  {
    height: '0.71',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Growlithe',
    weight: '19.0',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Growlithe.png',
  },
  {
    height: '6.50',
    weakness: '["Electric", "Rock"]',
    name: 'Gyarados',
    weight: '235.0',
    types: '["Water", "Flying"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Gyarados.png',
  },
  {
    height: '1.60',
    weakness: '["Ground", "Psychic", "Ghost", "Dark"]',
    name: 'Haunter',
    weight: '0.1',
    types: '["Ghost", "Poison"]',
    mainType: 'Ghost',
    image: 'e3aa059cc520f04244e4-Haunter.png',
  },
  {
    height: '1.40',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Hitmonchan',
    weight: '50.2',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Hitmonchan.png',
  },
  {
    height: '1.50',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Hitmonlee',
    weight: '49.8',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Hitmonlee.png',
  },
  {
    height: '0.41',
    weakness: '["Electric", "Grass"]',
    name: 'Horsea',
    weight: '8.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Horsea.png',
  },
  {
    height: '1.60',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Hypno',
    weight: '75.6',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Hypno.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Ivysaur',
    weight: '13.0',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Ivysaur.png',
  },
  {
    height: '0.51',
    weakness: '["Fighting"]',
    name: 'Jigglypuff',
    weight: '5.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Jigglypuff.png',
  },
  {
    height: '0.79',
    weakness: '["Ground"]',
    name: 'Jolteon',
    weight: '24.5',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Jolteon.png',
  },
  {
    height: '1.40',
    weakness: '["Fire", "Bug", "Rock", "Ghost", "Dark", "Steel"]',
    name: 'Jynx',
    weight: '40.6',
    types: '["Ice", "Psychic"]',
    mainType: 'Ice',
    image: 'e3aa059cc520f04244e4-Jynx.png',
  },
  {
    height: '0.51',
    weakness: '["Electric", "Grass", "Fighting", "Ground"]',
    name: 'Kabuto',
    weight: '11.5',
    types: '["Rock", "Water"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Kabuto.png',
  },
  {
    height: '1.30',
    weakness: '["Electric", "Grass", "Fighting", "Ground"]',
    name: 'Kabutops',
    weight: '40.5',
    types: '["Rock", "Water"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Kabutops.png',
  },
  {
    height: '1.30',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Kadabra',
    weight: '56.5',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Kadabra.png',
  },
  {
    height: '0.61',
    weakness: '["Fire", "Flying", "Psychic", "Rock"]',
    name: 'Kakuna',
    weight: '10.0',
    types: '["Bug", "Poison"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Kakuna.png',
  },
  {
    height: '2.21',
    weakness: '["Fighting"]',
    name: 'Kangaskhan',
    weight: '80.0',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Kangaskhan.png',
  },
  {
    height: '1.30',
    weakness: '["Electric", "Grass"]',
    name: 'Kingler',
    weight: '60.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Kingler.png',
  },
  {
    height: '0.61',
    weakness: '["Ground", "Psychic"]',
    name: 'Koffing',
    weight: '1.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Koffing.png',
  },
  {
    height: '0.41',
    weakness: '["Electric", "Grass"]',
    name: 'Krabby',
    weight: '6.5',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Krabby.png',
  },
  {
    height: '2.49',
    weakness: '["Electric", "Grass", "Fighting", "Rock"]',
    name: 'Lapras',
    weight: '220.0',
    types: '["Water", "Ice"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Lapras.png',
  },
  {
    height: '1.19',
    weakness: '["Fighting"]',
    name: 'Lickitung',
    weight: '65.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Lickitung.png',
  },
  {
    height: '1.60',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Machamp',
    weight: '130.0',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Machamp.png',
  },
  {
    height: '1.50',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Machoke',
    weight: '70.5',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Machoke.png',
  },
  {
    height: '0.79',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Machop',
    weight: '19.5',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Machop.png',
  },
  {
    height: '0.89',
    weakness: '["Electric", "Grass"]',
    name: 'Magikarp',
    weight: '10.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Magikarp.png',
  },
  {
    height: '1.30',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Magmar',
    weight: '44.5',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Magmar.png',
  },
  {
    height: '0.30',
    weakness: '["Fire", "Water", "Ground"]',
    name: 'Magnemite',
    weight: '6.0',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Magnemite.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Water", "Ground"]',
    name: 'Magneton',
    weight: '60.0',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Magneton.png',
  },
  {
    height: '0.51',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Mankey',
    weight: '28.0',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Mankey.png',
  },
  {
    height: '0.99',
    weakness: '["Water", "Grass", "Ice"]',
    name: 'Marowak',
    weight: '45.0',
    types: '["Ground"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Marowak.png',
  },
  {
    height: '0.41',
    weakness: '["Fighting"]',
    name: 'Meowth',
    weight: '4.2',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Meowth.png',
  },
  {
    height: '0.71',
    weakness: '["Fire", "Flying", "Rock"]',
    name: 'Metapod',
    weight: '9.9',
    types: '["Bug"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Metapod.png',
  },
  {
    height: '0.41',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Mew',
    weight: '4.0',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Mew.png',
  },
  {
    height: '2.01',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Mewtwo',
    weight: '122.0',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-Mewtwo.png',
  },
  {
    height: '2.01',
    weakness: '["Water", "Electric", "Rock"]',
    name: 'Moltres',
    weight: '60.0',
    types: '["Fire", "Flying"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Moltres.png',
  },
  {
    height: '1.30',
    weakness: '["Bug", "Ghost", "Dark"]',
    name: 'Mr. Mime',
    weight: '54.5',
    types: '["Psychic"]',
    mainType: 'Psychic',
    image: 'e3aa059cc520f04244e4-MrMime.png',
  },
  {
    height: '1.19',
    weakness: '["Ground", "Psychic"]',
    name: 'Muk',
    weight: '30.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Muk.png',
  },
  {
    height: '1.40',
    weakness: '["Water", "Ice", "Ground", "Psychic"]',
    name: 'Nidoking',
    weight: '62.0',
    types: '["Poison", "Ground"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Nidoking.png',
  },
  {
    height: '1.30',
    weakness: '["Water", "Ice", "Ground", "Psychic"]',
    name: 'Nidoqueen',
    weight: '60.0',
    types: '["Poison", "Ground"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Nidoqueen.png',
  },
  {
    height: '0.41',
    weakness: '["Ground", "Psychic"]',
    name: 'Nidoran ♀ (Female)',
    weight: '7.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-NidoranFemale.png',
  },
  {
    height: '0.51',
    weakness: '["Ground", "Psychic"]',
    name: 'Nidoran ♂ (Male)',
    weight: '9.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-NidoranMale.png',
  },
  {
    height: '0.79',
    weakness: '["Ground", "Psychic"]',
    name: 'Nidorina',
    weight: '20.0',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Nidorina.png',
  },
  {
    height: '0.89',
    weakness: '["Ground", "Psychic"]',
    name: 'Nidorino',
    weight: '19.5',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Nidorino.png',
  },
  {
    height: '1.09',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Ninetales',
    weight: '19.9',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Ninetales.png',
  },
  {
    height: '0.51',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Oddish',
    weight: '5.4',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Oddish.png',
  },
  {
    height: '0.41',
    weakness: '["Electric", "Grass", "Fighting", "Ground"]',
    name: 'Omanyte',
    weight: '7.5',
    types: '["Rock", "Water"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Omanyte.png',
  },
  {
    height: '0.99',
    weakness: '["Electric", "Grass", "Fighting", "Ground"]',
    name: 'Omastar',
    weight: '35.0',
    types: '["Rock", "Water"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Omastar.png',
  },
  {
    height: '8.79',
    weakness: '["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"]',
    name: 'Onix',
    weight: '210.0',
    types: '["Rock", "Ground"]',
    mainType: 'Rock',
    image: 'e3aa059cc520f04244e4-Onix.png',
  },
  {
    height: '0.30',
    weakness: '["Fire", "Ice", "Poison", "Flying", "Bug", "Rock"]',
    name: 'Paras',
    weight: '5.4',
    types: '["Bug", "Grass"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Paras.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Ice", "Poison", "Flying", "Bug", "Rock"]',
    name: 'Parasect',
    weight: '29.5',
    types: '["Bug", "Grass"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Parasect.png',
  },
  {
    height: '0.99',
    weakness: '["Fighting"]',
    name: 'Persian',
    weight: '32.0',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Persian.png',
  },
  {
    height: '1.50',
    weakness: '["Electric", "Rock"]',
    name: 'Pidgeot',
    weight: '39.5',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Pidgeot.png',
  },
  {
    height: '1.09',
    weakness: '["Electric", "Rock"]',
    name: 'Pidgeotto',
    weight: '30.0',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Pidgeotto.png',
  },
  {
    height: '0.30',
    weakness: '["Electric", "Rock"]',
    name: 'Pidgey',
    weight: '1.8',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Pidgey.png',
  },
  {
    height: '0.41',
    weakness: '["Ground"]',
    name: 'Pikachu',
    weight: '6.0',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Pikachu.png',
  },
  {
    height: '1.50',
    weakness: '["Fire", "Flying", "Rock"]',
    name: 'Pinsir',
    weight: '55.0',
    types: '["Bug"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Pinsir.png',
  },
  {
    height: '0.61',
    weakness: '["Electric", "Grass"]',
    name: 'Poliwag',
    weight: '12.4',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Poliwag.png',
  },
  {
    height: '0.99',
    weakness: '["Electric", "Grass"]',
    name: 'Poliwhirl',
    weight: '20.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Poliwhirl.png',
  },
  {
    height: '1.30',
    weakness: '["Electric", "Grass", "Flying", "Psychic", "Fairy"]',
    name: 'Poliwrath',
    weight: '54.0',
    types: '["Water", "Fighting"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Poliwrath.png',
  },
  {
    height: '0.99',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Ponyta',
    weight: '30.0',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Ponyta.png',
  },
  {
    height: '0.79',
    weakness: '["Fighting"]',
    name: 'Porygon',
    weight: '36.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Porygon.png',
  },
  {
    height: '0.99',
    weakness: '["Flying", "Psychic", "Fairy"]',
    name: 'Primeape',
    weight: '32.0',
    types: '["Fighting"]',
    mainType: 'Fighting',
    image: 'e3aa059cc520f04244e4-Primeape.png',
  },
  {
    height: '0.79',
    weakness: '["Electric", "Grass"]',
    name: 'Psyduck',
    weight: '19.6',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Psyduck.png',
  },
  {
    height: '0.79',
    weakness: '["Ground"]',
    name: 'Raichu',
    weight: '30.0',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Raichu.png',
  },
  {
    height: '1.70',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Rapidash',
    weight: '95.0',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Rapidash.png',
  },
  {
    height: '0.71',
    weakness: '["Fighting"]',
    name: 'Raticate',
    weight: '18.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Raticate.png',
  },
  {
    height: '0.30',
    weakness: '["Fighting"]',
    name: 'Rattata',
    weight: '3.5',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Rattata.png',
  },
  {
    height: '1.91',
    weakness: '["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"]',
    name: 'Rhydon',
    weight: '120.0',
    types: '["Ground", "Rock"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Rhydon.png',
  },
  {
    height: '0.99',
    weakness: '["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"]',
    name: 'Rhyhorn',
    weight: '115.0',
    types: '["Ground", "Rock"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Rhyhorn.png',
  },
  {
    height: '0.61',
    weakness: '["Water", "Grass", "Ice"]',
    name: 'Sandshrew',
    weight: '12.0',
    types: '["Ground"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Sandshrew.png',
  },
  {
    height: '0.99',
    weakness: '["Water", "Grass", "Ice"]',
    name: 'Sandslash',
    weight: '29.5',
    types: '["Ground"]',
    mainType: 'Ground',
    image: 'e3aa059cc520f04244e4-Sandslash.png',
  },
  {
    height: '1.50',
    weakness: '["Fire", "Electric", "Ice", "Flying", "Rock"]',
    name: 'Scyther',
    weight: '56.0',
    types: '["Bug", "Flying"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Scyther.png',
  },
  {
    height: '1.19',
    weakness: '["Electric", "Grass"]',
    name: 'Seadra',
    weight: '25.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Seadra.png',
  },
  {
    height: '1.30',
    weakness: '["Electric", "Grass"]',
    name: 'Seaking',
    weight: '39.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Seaking.png',
  },
  {
    height: '1.09',
    weakness: '["Electric", "Grass"]',
    name: 'Seel',
    weight: '90.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Seel.png',
  },
  {
    height: '0.30',
    weakness: '["Electric", "Grass"]',
    name: 'Shellder',
    weight: '4.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Shellder.png',
  },
  {
    height: '1.60',
    weakness: '["Electric", "Grass", "Bug", "Ghost", "Dark"]',
    name: 'Slowbro',
    weight: '78.5',
    types: '["Water", "Psychic"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Slowbro.png',
  },
  {
    height: '1.19',
    weakness: '["Electric", "Grass", "Bug", "Ghost", "Dark"]',
    name: 'Slowpoke',
    weight: '36.0',
    types: '["Water", "Psychic"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Slowpoke.png',
  },
  {
    height: '2.11',
    weakness: '["Fighting"]',
    name: 'Snorlax',
    weight: '460.0',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Snorlax.png',
  },
  {
    height: '0.30',
    weakness: '["Electric", "Rock"]',
    name: 'Spearow',
    weight: '2.0',
    types: '["Normal", "Flying"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Spearow.png',
  },
  {
    height: '0.51',
    weakness: '["Electric", "Grass"]',
    name: 'Squirtle',
    weight: '9.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Squirtle.png',
  },
  {
    height: '1.09',
    weakness: '["Electric", "Grass", "Bug", "Ghost", "Dark"]',
    name: 'Starmie',
    weight: '80.0',
    types: '["Water", "Psychic"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Starmie.png',
  },
  {
    height: '0.79',
    weakness: '["Electric", "Grass"]',
    name: 'Staryu',
    weight: '34.5',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Staryu.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Ice", "Poison", "Flying", "Bug"]',
    name: 'Tangela',
    weight: '35.0',
    types: '["Grass"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Tangela.png',
  },
  {
    height: '1.40',
    weakness: '["Fighting"]',
    name: 'Tauros',
    weight: '88.4',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Tauros.png',
  },
  {
    height: '0.89',
    weakness: '["Electric", "Ground", "Psychic"]',
    name: 'Tentacool',
    weight: '45.5',
    types: '["Water", "Poison"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Tentacool.png',
  },
  {
    height: '1.60',
    weakness: '["Electric", "Ground", "Psychic"]',
    name: 'Tentacruel',
    weight: '55.0',
    types: '["Water", "Poison"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Tentacruel.png',
  },
  {
    height: '0.99',
    weakness: '["Electric", "Grass"]',
    name: 'Vaporeon',
    weight: '29.0',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Vaporeon.png',
  },
  {
    height: '1.50',
    weakness: '["Fire", "Flying", "Psychic", "Rock"]',
    name: 'Venomoth',
    weight: '12.5',
    types: '["Bug", "Poison"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Venomoth.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Flying", "Psychic", "Rock"]',
    name: 'Venonat',
    weight: '30.0',
    types: '["Bug", "Poison"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Venonat.png',
  },
  {
    height: '2.01',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Venusaur',
    weight: '100.0',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Venusaur.png',
  },
  {
    height: '1.70',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Victreebel',
    weight: '15.5',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Victreebel.png',
  },
  {
    height: '1.19',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Vileplume',
    weight: '18.6',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Vileplume.png',
  },
  {
    height: '0.51',
    weakness: '["Ground"]',
    name: 'Voltorb',
    weight: '10.4',
    types: '["Electric"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Voltorb.png',
  },
  {
    height: '0.61',
    weakness: '["Water", "Ground", "Rock"]',
    name: 'Vulpix',
    weight: '9.9',
    types: '["Fire"]',
    mainType: 'Fire',
    image: 'e3aa059cc520f04244e4-Vulpix.png',
  },
  {
    height: '0.99',
    weakness: '["Electric", "Grass"]',
    name: 'Wartortle',
    weight: '22.5',
    types: '["Water"]',
    mainType: 'Water',
    image: 'e3aa059cc520f04244e4-Wartortle.png',
  },
  {
    height: '0.30',
    weakness: '["Fire", "Flying", "Psychic", "Rock"]',
    name: 'Weedle',
    weight: '3.2',
    types: '["Bug", "Poison"]',
    mainType: 'Bug',
    image: 'e3aa059cc520f04244e4-Weedle.png',
  },
  {
    height: '0.99',
    weakness: '["Fire", "Ice", "Flying", "Psychic"]',
    name: 'Weepinbell',
    weight: '6.4',
    types: '["Grass", "Poison"]',
    mainType: 'Grass',
    image: 'e3aa059cc520f04244e4-Weepinbell.png',
  },
  {
    height: '1.19',
    weakness: '["Ground", "Psychic"]',
    name: 'Weezing',
    weight: '9.5',
    types: '["Poison"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Weezing.png',
  },
  {
    height: '0.99',
    weakness: '["Fighting"]',
    name: 'Wigglytuff',
    weight: '12.0',
    types: '["Normal"]',
    mainType: 'Normal',
    image: 'e3aa059cc520f04244e4-Wigglytuff.png',
  },
  {
    height: '1.60',
    weakness: '["Ice", "Rock"]',
    name: 'Zapdos',
    weight: '52.6',
    types: '["Electric", "Flying"]',
    mainType: 'Electric',
    image: 'e3aa059cc520f04244e4-Zapdos.png',
  },
  {
    height: '0.79',
    weakness: '["Electric", "Ice", "Psychic", "Rock"]',
    name: 'Zubat',
    weight: '7.5',
    types: '["Poison", "Flying"]',
    mainType: 'Poison',
    image: 'e3aa059cc520f04244e4-Zubat.png',
  },
];

export default SeedPokemons;
